use_frameworks!

platform :ios, '8.0'

target 'HTWebView_Example' do
  pod 'HLTWebView', :path => '../'

  target 'HTWebView_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
  
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end

